CREATE CLASS SearchRun EXTENDS V;
CREATE PROPERTY SearchRun.run_id STRING;
CREATE PROPERTY SearchRun.query STRING;
CREATE PROPERTY SearchRun.model STRING;
CREATE PROPERTY SearchRun.started_at DATETIME;
CREATE PROPERTY SearchRun.finished_at DATETIME;
CREATE PROPERTY SearchRun.sources_count INTEGER;
CREATE PROPERTY SearchRun.candidates_count INTEGER;
CREATE PROPERTY SearchRun.ranked_count INTEGER;
CREATE PROPERTY SearchRun.saved_count INTEGER;
CREATE PROPERTY SearchRun.status STRING;
CREATE PROPERTY SearchRun.error STRING;

CREATE CLASS NewsLink EXTENDS V;
CREATE PROPERTY NewsLink.run_id STRING;
CREATE PROPERTY NewsLink.url STRING;
CREATE PROPERTY NewsLink.title STRING;
CREATE PROPERTY NewsLink.source STRING;
CREATE PROPERTY NewsLink.source_name STRING;
CREATE PROPERTY NewsLink.published_at DATETIME;
CREATE PROPERTY NewsLink.domain STRING;
CREATE PROPERTY NewsLink.query STRING;
CREATE PROPERTY NewsLink.llm_score DOUBLE;
CREATE PROPERTY NewsLink.reason STRING;
CREATE PROPERTY NewsLink.keywords STRING;
CREATE PROPERTY NewsLink.created_at DATETIME;

CREATE CLASS Source EXTENDS V;
CREATE PROPERTY Source.name STRING;
CREATE PROPERTY Source.domain STRING;
CREATE PROPERTY Source.created_at DATETIME;

CREATE CLASS Topic EXTENDS V;
CREATE PROPERTY Topic.name STRING;
CREATE PROPERTY Topic.created_at DATETIME;

CREATE CLASS ModelRun EXTENDS V;
CREATE PROPERTY ModelRun.run_id STRING;
CREATE PROPERTY ModelRun.model STRING;
CREATE PROPERTY ModelRun.raw_response STRING;
CREATE PROPERTY ModelRun.created_at DATETIME;

CREATE CLASS AnalyzedAs EXTENDS E;
CREATE CLASS Found EXTENDS E;
CREATE CLASS FromSource EXTENDS E;
CREATE CLASS About EXTENDS E;
CREATE CLASS AnalyzedBy EXTENDS E;
